[versions]

kotlinx-coroutines = "1.7.2"
kotlinx-serialization = "1.5.1"
kotlinx-atomicfu = "0.21.0"
uuid = "0.7.1"
postgresql-jdbc = "42.6.0"
hikaricp = "5.0.1"

[libraries]

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

kotlinx-atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "kotlinx-atomicfu" }

kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-cbor = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-cbor", version.ref = "kotlinx-serialization" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "kotlinx-serialization" }

uuid = { group = "com.benasher44", name = "uuid", version.ref = "uuid" }

postgresql-jdbc = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql-jdbc" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
